### ISSUE TITLE
Bunch of errors - is it ok?

### ISSUE THREAD

**Issue by moravcik** [thoughtram/angular2-master-class-starter#4]
Basically the application seems to work, but there are few problems:
- unmet dependencies for `typescript` and `rxjs` when doing `npm install`
- bunch of errors when running `ng serve` - seems like every type from Typescript cannot be found
- bunch of errors in console like `Cannot find global type 'Array'`. (seems pretty same as the errors from ng serve)

is it OK to live with that or I am missing something?

**Comment by cburgdorf** [comment]
Hey Michal,

thanks you for testing these things out early on before the actual training. So the unmet peer dependencies shouldn't worry you. They are expected in this setup and will probably go away with future versions.

The missing types are unexpected though. You can probably live with it but it's ruining the debugging experience a bit.

Let's figure out what's wrong.

Can you let me know:

- your environment
- your version of node
- your version of npm

Can you also give me the output of `tsc --version` as well as `./node_modules/typescript/bin/tsc --version` from the app directory.

A quick google search also revealed this one: https://github.com/angular/angular-cli/issues/1917

**Comment by billdwhite** [comment]
The "Cannot find" messages started popping up yesterday for me too.  Has something to do with Angular-Cli and Typescript 2.0.2.  Locking your project's typescript to 2.0.0 (by removing the ^ in package.json) fixes it, BUT, Angular RC6 just came out today and uses 2.0.2 so things might be at an impasse until that gets resolved.

**Comment by cburgdorf** [comment]
Good point about the locking! We actually always used to lock the version for our training material and this time it slipped through. I just fixed that.

Regarding RC6, we are going to use RC5 for the training. We were holding back for RC6 but it came to late and by now there's not enough time left to make all the changes to our material. Also many attendees have probably cloned the starter already and we don't want people to clone again. It adds chaos and suddenly you end up with some people being on RC5 others on RC6 and so on :)

**Comment by moravcik** [comment]
Hi Christoph, sorry for my late reply. 

My environment is as follows:

- Laptop Lenovo T540p with Ubuntu 16.04 LTS (upgraded from 14.04 LTS)
- Node.js version 6.5.0 (I have tried also 6.4.0 and 6.3.1 with same results)
- npm version 3.10.3
- `tsc --version` gives `message TS6029: Version 1.5.0-beta` (sounds a bit weird)
- `./node_modules/typescript/bin/tsc --version` gives `Version 2.0.0` (now, after fixing the version to 2.0.0)

Actually after fixing the version of typescript to 2.0.0 I am still getting unmet peer dependencies after `npm install`, but after `ng serve` I see no errors in terminal, just normal webpack output. And I see message from application "Angular 2 Master Class setup works!" in browser and no errors in console, which I believe is ok.

Btw, yes, it looked it was the issue you mentioned (angular/angular-cli#1917)
